name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      packages: write
      contents: write # required for goreleaser
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v2.5.0

      - name: Install Chainloop
        run: |
          curl -sfL https://chainloop.dev/install.sh | bash -s -- --version v${{ env.CL_VERSION }}

      - name: Initialize Attestation
        run: chainloop attestation init

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run Go Releaser
        id: release
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - uses: anchore/sbom-action@v0
        with:
          path: ./dist/
          format: cyclonedx-json
          artifact-name: sbom.cyclonedx.json
          output-file: /tmp/sbom.cyclonedx.json

      - name: Add Attestation Artifacts (binaries)
        run: |
          echo -n '${{ steps.release.outputs.artifacts }}' | jq -r '.[] | select(.type=="Binary" and .goos=="linux") | { "name": "\(.extra.ID)-\(.goos)-\(.goarch)", "path":"\(.path)"} | @base64' | while read i; do
              BINARY_NAME=$(echo "${i}" | base64 --decode | jq -r ${1} .name)
              BINARY_PATH=$(echo "${i}" | base64 --decode | jq -r ${1} .path)
              chainloop attestation add --name ${BINARY_NAME} --value ${BINARY_PATH} 
            done

      - name: Add Attestation Artifacts (SBOM)
        run: chainloop attestation add --name sbom --value /tmp/sbom.cyclonedx.json

      - name: Finish and Record Attestation
        if: ${{ success() }}
        run: |
          chainloop attestation status --full
          chainloop attestation push --key env://CHAINLOOP_SIGNING_KEY
        env:
          CHAINLOOP_SIGNING_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          CHAINLOOP_SIGNING_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Mark attestation as failed
        if: ${{ failure() }}
        run: |
          chainloop attestation reset

      - name: Mark attestation as cancelled
        if: ${{ cancelled() }}
        run: |
          chainloop attestation reset --trigger cancellation
    env:
      CL_VERSION: 0.8.70
      CHAINLOOP_ROBOT_ACCOUNT: ${{ secrets.CHAINLOOP_ROBOT_ACCOUNT_TOKEN }}
